import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
//import styles from '@essentials-nextjs/styles/Home.module.css'
import fetcher from '@essentials-nextjs/utils/fetcher'
import ImageOfTheDay from '@essentials-nextjs/components/ImageOfTheDay'
import Last10Images from '@essentials-nextjs/components/Last10Images'
import { ImageType } from '@essentials-nextjs/types'




const inter = Inter({ subsets: ['latin'] })
type HomeProps = {
  imageOfTheDayData: ImageType;
  last10ImagesData: ImageType[]
}

export default function Home({ imageOfTheDayData, last10ImagesData }: HomeProps) {
  // console.log(ImageOfTheDay)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <ImageOfTheDay {...imageOfTheDayData} />
        <Last10Images images={last10ImagesData} />
      </main>
    </>
  )
}

export async function getStaticProps() {
  try {
    //const response = await fetch('https://api.nasa.gov/planetary/apod?api_key=mdmaar2fc470uI5gzUuDvGrhMDcpPBjRSo26JPPW')

    //chequear datefns
    const imageOfTheDayData = await fetcher()
    const last10ImagesData = await fetcher('&start_date=2023-03-01&end_date=2023-03-10')

    return {
      props: {
        imageOfTheDayData, 
        last10ImagesData
      }
    }
  } catch (error) {
    console.log(error)
    return {}
  }
}
